name: Publish Development Build
on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checkout the repository
            - name: Checkout Repository
              uses: actions/checkout@v4

            # Set up Java
            - name: Set up Java
              uses: actions/setup-java@v4
              with:
                  java-version: 21
                  distribution: adopt

            # Grant execute permission for gradlew
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            # Build with Gradle
            - name: Build with Gradle
              run: ./gradlew build

            # Release build artifacts
            - name: Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  automatic_release_tag: latest
                  prerelease: true
                  title: DevBuild
                  files: |
                      ./build/libs/*.jar
